spring:
  profiles: default

logging:
  level:
    com:
      viirrtus:
        queueOverHttp: DEBUG

app:
  persistence:
    file:
      storageDirectory: "persist"
  brokers:
    - name: "Kafka"
      origin: "kafka"
      config:
        bootstrap.servers: "localhost:9092"
#        bootstrap.servers: "192.168.99.100:9092"