version: '2.1'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '10.100.80.47:9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.100.80.47:9092
    #    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092;
    #    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.99.100:9092
    depends_on:
      - 'zookeeper'
